server:
  port: 8081

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.finastra: DEBUG
ffdcapi:
  baseUrl: https://api.fusionfabric.cloud
  loginUrl: ${ffdcapi.baseUrl}/login/v1

auth:
  keyId: <%keyID%>
  strong: false

finastra:
    oauth2:
      client:
        grant-type: client_credentials
        clientId: <%YOUR-CLIENT-ID%>
        clientSecret: <%YOUR-SECRET-KEY%>
        accessTokenUri: ${ffdcapi.loginUrl}/sandbox/oidc/token
        scope: openid
