server:
  port: 8081

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.finastra: DEBUG
ffdcapi:
  baseUrl: https://api.fusionfabric.cloud
  loginUrl: ${ffdcapi.baseUrl}/login/v1

auth:
  strong: false

spring:
  security:
    oauth2:
      client:
        registration:
          finastra:
            client-id: <%YOUR-CLIENT-ID%>
            client-secret: <%YOUR-SECRET-KEY%>
            authorization-grant-type: client_credentials
        provider:
          finastra:
            token-uri: ${ffdcapi.loginUrl}/sandbox/oidc/token